server:
  servlet:
    context-path: /api
  port: 8080

spring:
 mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
 datasource:
   url: jdbc:postgresql://localhost:5432/postgres?currentSchema=employees-db
   username: postgres
   password: 1234
   driverClassName: org.postgresql.Driver

 jpa:
   show-sql: true
   database-platform: org.hibernate.dialect.PostgreSQLDialect
   hibernate:
    ddl-auto: update   